services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000  
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "5050:5050"
    environment:
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - PYTHONPATH=/app/app
    volumes:
      - ./backend:/app
    command: >
      /bin/bash -c "python app.py"
    
    
